name: 'check_localization_php'
description: 'github action template for check if need do localization from ru lang'
author: 'Anton Koshel <fxpw@outlook.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'eye'  
  color: 'gray-dark'